name: disable tenant

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Start PostgreSQL
#        run: docker run --name postgres -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d postgres:alpine
      - name: Start Okapi
        run: |
          docker create --name okapi folioorg/okapi:4.14.4
          docker cp okapi:/usr/verticles/okapi-core-fat.jar okapi-core-fat.jar
          docker rm -f okapi
          OKAPI=http://`docker network inspect --format='{{range .IPAM.Config}}{{.Gateway}}{{end}}' bridge`:9130
          java -Dokapiurl=$OKAPI -jar okapi-core-fat.jar dev &
      - name: Start mod-authtoken
        run: |
          docker create --name mod-authtoken folioorg/mod-authtoken:2.11.0
          docker cp mod-authtoken:/usr/verticles/mod-authtoken-fat.jar mod-authtoken-fat.jar
          docker rm -f mod-authtoken
          export DB_HOST=localhost
          export DB_PORT=5432
          export DB_DATABASE=postgres
          export DB_USERNAME=postgres
          export DB_PASSWORD=postgres
          java -jar mod-authtoken-fat.jar &
      - name: Okapi health
        run: curl --retry 30 --retry-delay 1 --retry-connrefused -sS http://localhost:9130/_/proxy/health
      - name: mod-authtoken health
        run: curl --retry 30 --retry-delay 1 --retry-connrefused -sS http://localhost:8081/admin/health
      - name: List nodes
        run: |
          curl -sS -D - -H "Content-type: application/json" http://localhost:9130/_/discovery/nodes
      - name: Enable tenant
        run: |
          curl -sS -D - -H "Content-type: application/json" -d '{"id": "diku"}' http://localhost:9130/_/proxy/tenants
      - name: Declare module
        run: |
          curl -sS -D - -H "Content-type: application/json" -d @ModuleDescriptor.json http://localhost:9130/_/proxy/modules
      - name: Deploy module
        run: |
          curl -sS -D - -H "Content-type: application/json" -d '{"srvcId": "mod-authtoken-2.11.0", "instId":"mod-authtoken-2.11.0", "url": "http://localhost:8081"}' http://localhost:9130/_/discovery/modules
      - name: Enable module for tenant
        run: |
          curl -sS -D - -H "Content-type: application/json" -d '{"id": "mod-authtoken-2.11.0"}' http://localhost:9130/_/proxy/tenants/diku/modules
      - name: Disable module for tenant
        run: |
          curl -s -S -D - -XDELETE http://localhost:9130/_/proxy/tenants/diku/modules/mod-authtoken-2.11.0
